services:
  - type: web
    name: car-marketplace-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://car-marketplace-backend.onrender.com
      - key: VITE_AI_API_URL
        value: https://ai-car-recommendation-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 