services:
  - type: web
    name: car-marketplace-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: http://localhost:5173,http://localhost:3000
    healthCheckPath: /health 