services:
  - type: web
    name: ai-car-recommendation-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: WORKERS
        value: 1
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com,http://localhost:5173
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-mpnet-base-v2
      - key: TOP_K_RECOMMENDATIONS
        value: 10
      - key: SIMILARITY_THRESHOLD
        value: 0.3
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: false
      - key: CACHE_EMBEDDINGS
        value: true
      - key: CACHE_FILE
        value: car_embeddings_cache.pkl
    healthCheckPath: /
    autoDeploy: true 